add front end and backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,17 +1,84 @@
+# version: 2.1
+
+# jobs:
+#   my_job:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - run: exit 1
+#       - run:
+#           name: on error
+#           command: echo "Hello Error!"
+#           when: on_fail
+
+# workflows:
+#   my_workflow:
+#     jobs:
+#       - my_job
+
 version: 2.1
 
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      # Add parameter here
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            echo "Hello Error!"
+            exit 1
+
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
+
 jobs:
-  my_job:
+  build-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
-      - run: exit 1
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
       - run:
-          name: on error
-          command: echo "Hello Error!"
-          when: on_fail
+          name: Build front-end
+          command: |
+            echo "Hello Error!"
+            exit 1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
 
-workflows:
-  my_workflow:
-    jobs:
-      - my_job
+  build-backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Back-end build
+          command: |
+            echo "Hello Error!"
+            exit 1
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
